version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://crm_user:crm_password@postgres:5432/crm_db
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-change-in-production}
      FLASK_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crm-network
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - crm-network
    environment:
      VITE_API_URL: http://localhost/api

networks:
  crm-network:
    driver: bridge

volumes:
  postgres_data: